# Getting ready

## Get Visual Studio Code ready

Visual Studio Code (VS Code) is a lightweight, cross-platform code editor developed by Microsoft. It’s free, open source, and supports a wide range of programming languages.

1. Download Visual studio code: https://code.visualstudio.com/download
2. Using the extension manager, install the following plugins:
- **Python** by Microsoft
- **Snakemake Language** by Snakemake
- **Remote - SSH** by Microsoft
- **Remote Explorer** by Microsoft

## Create a SSH connection to Mjolnir

1. Ensure you are connected to the KU VPN
2. Menu: View > Command Palette > Remote-SSH: Connect to Host
3. + Add New SSH Host
4. ssh mjolnirgate.unicph.domain
5. Type password

This should have created a SSH connection to Mjolnir, which will enable you to create a Remote Explorewr.

## Open the remote explorer

1. Explorer
2. Connect to remote > Open Folder
3. Use the following path: /maps/projects/course_2/people/{your_ku_id}

## Copy exercise files to your personal directory

```{sh eval=FALSE}
cp -r /maps/projects/course_2/data/* .
```

## Useful aliases

Let's declare some useful aliases to make the work a bit more pleasant. 

```{sh eval=FALSE}
# Generate the file containing the aliases
cat <<EOF > aliases
alias myjobs='squeue -u ${user} --format="%.18i %.9P %.30j %.8u %.8T %.10M %.9l %.6m %k" --me'
alias screens='screen -list'
EOF

# Source the aliases
source aliases
```

## Screen session

Screen is a simple tool that keeps your command-line session running on a server even if your internet drops or you close your laptop. Think of it like putting your terminal in a locker—you can step away and later unlock it to find everything exactly where you left it. It also lets you make several “tabs” (windows) inside one SSH login and switch between them. On HPC clusters where tasks can run for hours, starting them inside Screen keeps them safe and easy to rejoin. It’s lightweight and saves you from losing work.

To create a screen session for the entire duration of the workshop:

```{sh eval=FALSE}
screen -S snakemake_workshop
```

To get out from the session, you must type `ctrl+a d`

To re-enter the session, simply:

```{sh eval=FALSE}
screen -r snakemake_workshop
```

And to close the session, just type `exit`.

## Interactive job

On a shared cluster like Mjolnir, the entry (login) nodes are the front door: they’re meant for quick, lightweight tasks like connecting, moving files, loading modules, editing scripts, and submitting jobs. They are shared by everyone and deliberately constrained (CPU, memory, long-running limits). Running heavy computations there slows the system for all users and can trigger automatic kills from cluster policies. An interactive session gives you a reserved slice of the compute nodes through the scheduler (e.g., Slurm).

When you are in the entry node, the following command should return.

```{sh eval=FALSE}
hostname
```

```
mjolnirgate01fl.unicph.domain
```

In this workshop, each participant will get allocated 4 CPUs and 16GB of memory at node mjolnircomp14fl. When that time is over, the session will close automatically.

```{sh eval=FALSE}
srun \
  --job-name=snakemake_workshop \
  --account=teaching \
  --reservation=snakemake_hackaton \
  --partition=cpuqueue \
  --nodes=1 \
  --nodelist=mjolnircomp14fl \
  --time=08:00:00 \
  --mem=16G \
  --cpus-per-task=4 \
  --pty bash -I
```

This will display for a few seconds, after which you will get connected to the computation node.

```
srun: job XXXXXXXXX queued and waiting for resources
```

To verify you are in the computing node the `hostname` command should now display:

```
mjolnircomp14fl.unicph.domain
```

To exit the interactive job, just type `exit`.

## Required modules

We will need to load two key modules to run the workshop. If you have your own conda, consider deactivating it temporarily to ensure the exercises run smoothly.

```{sh eval=FALSE}
# Ensure there is nothing loaded
module purge

# Load the relevant modules
module load snakemake/9.4.0
module load miniconda/py39_23.1

# List the loaded modules
module list
```

Use should see exactly this:

```
Currently Loaded Modulefiles:
 1) miniconda/py39_23.1   2) snakemake/9.4.0
```

## Let's go!

Now we are ready to go!